# see https://jekyllrb.com/docs/configuration/
theme: jekyll-theme-cayman
source: ./src/
destination: ./docs/
url: https://pasdoc.github.io/

# see https://github.com/pages-themes/cayman
title: PasDoc
description: Documentation tool for Pascal source code
show_downloads: true
github:
  zip_url: https://github.com/pasdoc/pasdoc/archive/v0.15.0.zip
