# see https://jekyllrb.com/docs/configuration/
# theme: jekyll-theme-hyde
theme: jekyll-theme-cayman
source: ./src/
destination: ./docs/
url: https://pasdoc.github.io/
include: ['_Sidebar.asciidoc']

# see https://github.com/pages-themes/cayman
title: PasDoc
description: Documentation tool for Pascal source code
show_downloads: true

# our custom theme variables:
pasdoc:
  repository_url: https://github.com/pasdoc/pasdoc
  download:
    linux_x86-64: https://sourceforge.net/projects/pasdoc/files/PasDoc%20Linux%20Amd64/pasdoc-0.15.0-linux-x86_64.tar.gz/download
    windows_i386: https://sourceforge.net/projects/pasdoc/files/PasDoc%20Windows/pasdoc-0.15.0-win32.zip/download
  main_url: index
