:doctitle: Compiling PasDoc from sources
:sectnums:
:toc: left
:toclevels: 4

## Get the source code

First of all, get https://github.com/pasdoc/pasdoc/[our source code from GitHub]. E.g.

```
git clone https://github.com/pasdoc/pasdoc.git
```

## [[fpc]] Build with command-line FPC

You can build with command-line https://www.freepascal.org/[Free Pascal Compiler (FPC)].

_Requirements_: We need FPC with `Generics.Collections` support, which implies FPC >= 3.2.0.

From the command-line, compile by simply executing

```
make
```

in the main repository directory.

[NOTE]
====
You must use _GNU make_.

- Under Linux this is the standard `make`.
- Under Windows it is included with FPC installation (you can also get it with http://www.mingw.org/[MinGW] or http://www.cygwin.com/[Cygwin]).
- Under FreeBSD it's called `gmake`.
- Under MacOS it's called `gmake` and you can install it with `brew install make` (using https://brew.sh/[Homebrew]).
====

### [[lazarus]] Build with Lazarus

https://www.lazarus-ide.org/[Lazarus is an IDE using FPC under the hood].

_Requirements_: Any Lazarus version that supports FPC >= 3.2.0 should be able to compile pasdoc.

- First, open and build the package with our components by installing `source/packages/lazarus/pasdoc_package.lpk`.

- Build the command-line PasDoc by opening the `source/console/pasdoc.lpi` project in Lazarus and compiling it.

- Build the GUI PasDoc by opening the `source/gui/pasdoc_gui.lpi` project in Lazarus and compiling it.

## [[delphi]] Build with Delphi

_Requirements_: Any Delphi with `Generics.Collections` support should be good, which in theory means >= 2009. We actively test (using GitHub Actions) with Delphi 10 and 12 right now.

To build the command-line PasDoc, open the Delphi project in `source/console/` and build as usual.

## [[see-also-release-making]] See also: release making

Compiling, testing and other things related to release making are described on this page: link:ReleaseMaking[ReleaseMaking].
