:doctitle: HTML Help Output
:sectnums:
:toc: left
:toclevels: 4

## Introduction

_HTML Help_ is a file format for documentation. The final documentation can be a single file with an extension `.chm` (for "_compiled html_"). It was designed by Microsoft, along with some proprietary tools to create and view it, but a number of cross-platform open-source viewers also exist now.

As the name suggests, the format is based on HTML. Internally, a `.chm` file is just a collection of HTML files, with some extra information. See https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help[Wikipedia] and http://msdn.microsoft.com/en-us/library/windows/desktop/ms524413(v=vs.85).aspx[Microsoft documentation] for more information.

link:index[PasDoc] can generate all the files necessary to create the _HTML Help_ documentation. We do not produce a ready `.chm` file -- but we generate all the prerequisites necessary. After generating the files, you can create the final CHM file using tools like `hhc` or `chmcmd`.

## Generating HTML Help files with PasDoc

First, generate documentation using pasdoc with `--format=htmlhelp` command-line option. In addition to normal HTML files, we will output files `docs.hhc`, `docs.hhk` and `docs.hhp`. You can change the names of these files to something else with link:NameOption[--name option].

Once this is done, you can create the final `.chm` file using one of the tools described below.

## Creating the final .chm file

### Microsoft HTML Help Workshop (Windows only, proprietary)

One option to create the final `.chm` file is to use https://msdn.microsoft.com/en-us/library/windows/desktop/ms669985(v=vs.85).aspx[HTML Help Workshop]. Unfortunately, the download links (on this Microsoft page) are broken, which has been https://learn.microsoft.com/en-us/answers/questions/265752/htmlhelp-workshop-download-for-chm-compiler-instalp[reported] but seems unlikely to be fixed.

Best options to get _HTML Help Workshop_ now:

1. Get it from the _Internet Archive_:
+
--
- http://web.archive.org/web/20160201063255/http://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe[htmlhelp.exe]
- http://web.archive.org/web/20160314043751/http://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/helpdocs.zip[helpdocs.zip]
--

2. Or install it using a https://chocolatey.org/[Chocolatey], a package manager for Windows. Install https://chocolatey.org/install[Chocolatey itself] first, using _PowerShell_, and then follow https://community.chocolatey.org/packages/html-help-workshop[installation instructions for `html-help-workshop` package].

In both cases, after the installation the tools are in `C:\Program Files (x86)\HTML Help Workshop` directory. You can add it to your `$PATH` to easily execute `hhc` from the command line.

To make `docs.chm` file:

* Interactively: run the `hhw` program from the _HTML Help Workshop_, open generated `docs.hhp` file, and run _"Compile HTML file"_ from toolbar.

* Or in batch mode (command line): run `hhc docs.hhp`.

That's it! You have `docs.chm` file.

### chmcmd (cross-platform, open-source)

Another option is to use cross-platform open-source tool `chmcmd` developed and distributed along with https://www.freepascal.org/[FPC]. Call it like this:

```
chmcmd --no-html-scan docs.hhp
```

This will again create `docs.chm` file.

## Custom help contents

Optionally, if you wish to use a custom help-contents file, you can specify a file name with the `--html-help-contents` option for PasDoc. Each line of the file specifies an entry in the help contents. Each space or tab character at the beginning of a line increases the level of the item in the contents by 1. The remainder of the line comprises a title for the item, an "=" character, and the link to which the item should be connected. For example: `An Item = MyPage.html`

