:doctitle: PasDoc
:sectnums:
:toc: left
:toclevels: 4

## Introduction

PasDoc is a documentation tool for the Object Pascal code
(as implemented by http://www.freepascal.org/[FPC] and
http://www.embarcadero.com/products/delphi[Delphi]).
Documentation is generated from comments found in the source code
and / or in dedicated "description files". Numerous output formats are supported, including HTML, LaTeX (for PDF, PS), XML and PHP.

This is a _free and open source software_.
//PasDoc itself is written using modern Object Pascal and can be build using FPC or Delphi.

We https://castle-engine.io/donate[appreciate your donations (Michalis, maintainer of PasDoc, also makes Castle Game Engine)], esp. if you use PasDoc in a commercial project. This helps us to continue developing and improving PasDoc.

## Basic Usage

Put comments before the identifiers in your Pascal source code. Like this:

```pascal
{ My amazing unit. }
unit MyUnit;

interface

type
  { My amazing class. }
  TMyClass = class
  private
    FMyProperty: String;
  public
    { My amazing method. }
    procedure MyMethod;
    { My amazing property. }
    property MyProperty: String read FMyProperty write FMyProperty;
  end;

implementation
// ...
end.
```

Process this source code with PasDoc, and get documentation in one of the output formats. From the command-line, you can do it like this:

```shell
mkdir -p output-dir/
pasdoc myunit.pas --format html --output output-dir
```

You can also use the GUI interface, see link:PasDocGui[PasDoc GUI].

## Examples

- Take a look at https://pasdoc.github.io/autodoc/html/index.html[PasDoc's own documentation (in the HTML format)].

- See link:PasDocAutoDoc[PasDoc's own documentation in all the formats].

- See link:ProjectsUsingPasDoc[Projects using PasDoc] for links to larger real-world
examples of how documentation generated by PasDoc looks like.

## Features

For more information on how to document your source code see:

- link:WhereToPlaceComments[Where To Place Comments]
- link:WritingDocumentation[Writing Documentation]
- link:SupportedTags[Supported Tags]

Available output formats:

* link:HtmlOutput[HTML] - modern webpage documenting your project
* link:HtmlHelp[HtmlHelp]
* link:LatexOutput[LaTeX] - you can use this to generate PDF or PostScript using LaTeX tools like `pdflatex`
* link:Latex2RtfOutput[Latex2rtf]
* link:SimpleXmlOutput[SimpleXml] - useful to process obtained information using your own tools, you only need to read the generated XML file
* link:PhpOutput[PHP] - PHP map from Pascal identifier -> HTML link, to implement searching/enumeration in PHP websites

Check out the link:CommandLine[CommandLine] to get a better feeling
for how PasDoc works.

See also the list of link:AdvancedFeatures[AdvancedFeatures] of PasDoc.

## All Downloads (Stable and Unstable)

Download:

* Latest *stable* PasDoc release https://github.com/pasdoc/pasdoc/releases/latest[can be downloaded from here].

* Latest *unstable* (automatic build after every commit, published once automatic tests pass) release https://github.com/pasdoc/pasdoc/releases/tag/snapshot[is available here ("snapshot" releases)].

You can watch our https://github.com/pasdoc/pasdoc/releases[releases page] or https://github.com/pasdoc/pasdoc/discussions/categories/announcements[announcements category in our discussions] to be notified about a new release.

## Get involved

https://github.com/pasdoc/pasdoc/discussions[We use GitHub Team Discussions] as our forum. Come and talk to us!

Use the https://github.com/pasdoc/pasdoc/issues[GitHub issues] to report bugs and feature requests. If you would like to contribute, it's best to https://github.com/pasdoc/pasdoc/pulls[submit a pull request using GitHub].

## Development

See the
https://github.com/pasdoc/pasdoc/blob/master/ChangeLog.md[ChangeLog] for
recent changes to PasDoc.

PasDoc source code:

* PasDoc is licensed under the
http://www.gnu.org/copyleft/gpl.html[GNU General Public License].
* You can get the latest PasDoc sources
https://github.com/pasdoc/pasdoc[from our project on GitHub].
In short, just call
+
----
git clone https://github.com/pasdoc/pasdoc.git
----
* See link:CompilingPasDoc[CompilingPasDoc] for instructions how to compile PasDoc.
* See link:ReleaseMaking[ReleaseMaking] to know how we test and package PasDoc for final releases.

While developing PasDoc we also developed some link:OtherTools[OtherTools] that you may find useful.

About these web pages:

* We are using wiki to easily update these pages. You are welcome to contribute to the documentation!
* All text within this wiki is licensed on terms of http://www.gnu.org/copyleft/gpl.html[GNU General Public License] (just like PasDoc sources).
