:doctitle: Process of making new PasDoc release
:sectnums:
:toc: left
:toclevels: 4

## Introduction

This page describes the process of making a new https://github.com/pasdoc/pasdoc/releases[PasDoc release]. Unless you're a PasDoc maintainer, you probably don't care about the details described here.

## Change version number to next stable

* Change version of all packages in `source/packages/`. Right now this means just changing `source/packages/lazarus/pasdoc_package.lpk`. (Delphi packages don't store PasDoc version now.)
* change `VERSION` in `pasdoc/Makefile`
* change `PASDOC_VERSION` and `PASDOC_DATE` in `source/components/PasDoc_Versions.pas`

Make last version number _even_ to signify stable release, like `1.2.4`.

## [[write-changelog-entry]] Write ChangeLog entry

Make sure you have nice entry in https://github.com/pasdoc/pasdoc/blob/master/ChangeLog.md file in pasdoc sources.

We try to update this changelog file _while_ developing PasDoc (each time someone does something significant, it's immediately added to the changelog). So at this point, mainly _review and finalize (write new verion number and release date) changelog entry_.

## [[update-docs]] Update docs

Remove from the documentation text

_Note that this feature is not available in latest released pasdoc version, x.y.z. You must download and compile pasdoc yourself or use link:DevelopmentSnapshots[DevelopmentSnapshots] to use this feature._

## Update AutoDoc

* It's a good idea to upload link:PasDocAutoDoc[PasDocAutoDoc] at this time, like this:
+
----
cd pasdoc/source/autodoc/
pasdoc --version # make sure latest version of pasdoc is used
make clean public upload

cd  ../../../pasdoc.github.io/
git commit -m "Updated autodoc"
git push
----

## Prepare tag and GitHub release

* Create a tag by `make tag`.

* Go to https://github.com/pasdoc/pasdoc/releases and create a new release from this tag. Place the notes from the changelog entry as description. Make it "draft" for now.

## [[compile-and-test-all-releases]] Build and test all releases (automated now)

Note: This step is automated now, using https://github.com/pasdoc/pasdoc/tree/master/.github/workflows[GitHub Actions] to automatically test and build PasDoc. Just switch `release_tag` in `.github/workflows/build.yml` to the new tag and push it, and GitHub Actions will do the rest.

Below we describe how to do things manually, just in case.

* Make sure you have the latest stable FPC and Lazarus versions.

* Run all the tests by
+
```
make tests
```
+
There are various comments inside `tests/run_all_tests.sh` about what is really happening. It runs various other tests we have prepared, it even compares the output with some "designated correct" output.
+
To be sure, you should run these tests on all targets.

* To build for the current platform (OS and architecture) call this:
+
```
make clean build-fpc-release
```
+
Note that it's important to call `clean` before `build-...`, otherwise you risk that some units were left as compiled with debug options.
+
To build for indicated platform and package to zip/tar.gz (this will call `clean build-fpc-release` as first steps):
+
```
make dist-<os/arch>
```

* The `make dist-...` will automatically compile and include `pasdoc_gui` binary (using `lazbuild` to compile Lazarus package and project in batch mode). But you can also compile it manually:
+
----
lazbuild source/packages/lazarus/pasdoc_package.lpk
lazbuild source/gui/pasdoc_gui.lpi
----
+
For basic test of `pasdoc_gui`, open the project with pasdoc's autodoc `source/autodoc/autodoc.pds` and hit "Generate".

## Make release public

* Make the release non-draft on GitHub.

* Mark it as "latest", make sure https://github.com/pasdoc/pasdoc/releases/latest[latest release] page links to it.

## Announce new release everywhere

* Announce new release on https://forum.lazarus.freepascal.org/[Lazarus forum].
* https://sourceforge.net/p/pasdoc/news/[SourceForge "Old News" item] _PasDoc x.y.z released_
* Announce new release on http://freshcode.club/projects/pasdoc.
* Send an update to http://directory.fsf.org/project/pasdoc/[FSF directory].

Really, really large and significant improvements may be signalled by
changing the project's description:

* on https://github.com/pasdoc/pasdoc/[GitHub]
* on https://sourceforge.net/projects/pasdoc/[SF project page]
* on http://wiki.lazarus.freepascal.org/Projects_using_Lazarus#PasDoc[Lazarus wiki "Projects Using Lazarus" page]

## Prepare for next release

* `ChangeLog.md` file should start with line
+
----
`## Upcoming Next Release`
----

- Repeat the steps from _"Change version number to next stable"_, but :
+
--
- Make last version number _odd_ to signify unstable release and add `.snapshot`, like `1.2.5.snapshot`.

- Update link:DevelopmentSnapshots[DevelopmentSnapshots] version number.
--