:doctitle: Process of making new PasDoc release
:sectnums:
:toc: left
:toclevels: 4

## Introduction

This page describes the process of making a new https://github.com/pasdoc/pasdoc/releases[PasDoc release]. Unless you're a PasDoc maintainer, you probably don't care about the details described here.

## Change version number to next stable

* Change version of all packages in `source/packages/`. Right now this means just changing `source/packages/lazarus/pasdoc_package.lpk`. (Delphi packages don't store PasDoc version now.)
* change `VERSION` in `pasdoc/Makefile`
* change `PASDOC_VERSION` and `PASDOC_DATE` in `source/components/PasDoc_Versions.pas`
* `make && ./bin/pasdoc --version` should show the new version number and date.
* `make dist-linux-x86_64` should create a tar.gz file with the new version number in its name.

Make last version number _even_ to signify stable release, like `1.2.4`.

## Write ChangeLog entry

Make sure you have nice entry in https://github.com/pasdoc/pasdoc/blob/master/ChangeLog.md file in pasdoc sources.

We try to update this changelog file _while_ developing PasDoc (each time someone does something significant, it's immediately added to the changelog). So at this point, mainly _review and finalize (write new verion number and release date) changelog entry_.

## Update docs

Remove from the documentation text

_Note that this feature is not available in latest released pasdoc version, x.y.z. You must download and compile pasdoc yourself or use link:DevelopmentSnapshots[DevelopmentSnapshots] to use this feature._

## Update AutoDoc

* It's a good idea to upload link:PasDocAutoDoc[PasDocAutoDoc] at this time, like this:
+
----
cd pasdoc/source/autodoc/
pasdoc --version # make sure latest version of pasdoc is used
make clean public upload

cd  ../../../pasdoc.github.io/
git commit -m "Updated autodoc"
git push
----

## Prepare tag and GitHub release

* Create a tag by `make tag`.

* Go to https://github.com/pasdoc/pasdoc/releases and create a new release from this tag. Place the notes from the changelog entry as description. Make it "draft" for now.

## [[compile-and-test-all-releases]] Build and test all releases (automated now)

Note: This step is automated now, using https://github.com/pasdoc/pasdoc/tree/master/.github/workflows[GitHub Actions] to automatically test and build PasDoc. Just switch `release_tag` in `.github/workflows/build.yml` to the new tag and push it, and GitHub Actions will do the rest.

Below we describe how to do things manually, just in case.

* Make sure you have the latest stable FPC and Lazarus versions.

* Run all the tests by
+
```
make tests
```
+
There are various comments inside `tests/run_all_tests.sh` about what is really happening. It runs various other tests we have prepared, it even compares the output with some "designated correct" output.
+
To be sure, you should run these tests on all targets.

* To build for the current platform (OS and architecture) call this:
+
```
make clean build-fpc-release
```
+
Note that it's important to call `clean` before `build-...`, otherwise you risk that some units were left as compiled with debug options.
+
To build for indicated platform and package to zip/tar.gz (this will call `clean build-fpc-release` as first steps):
+
```
make dist-<os/arch>
```

* The `make dist-...` will automatically compile and include `pasdoc_gui` binary (using `lazbuild` to compile Lazarus package and project in batch mode). But you can also compile it manually:
+
----
lazbuild source/packages/lazarus/pasdoc_package.lpk
lazbuild source/gui/pasdoc_gui.lpi
----
+
For basic test of `pasdoc_gui`, open the project with pasdoc's autodoc `source/autodoc/autodoc.pds` and hit "Generate".

## Make release public

* Make the release non-draft on GitHub.

* Mark it as "latest", make sure https://github.com/pasdoc/pasdoc/releases/latest[latest release] page links to it.

* Update our website to link to latest release:
+
--
- edit `_config.yml`
- edit also `src/_layouts/default.html` if plaforms changed.
- `make`
- commit and push
- once live, download all linked releases to make sure links are OK.
--

## Announce new release everywhere

* Make thread on our forum: https://github.com/pasdoc/pasdoc/discussions .
+
--
- GitHub's new _"Create discussion from release"_ checkbox also does it OK (make sure it's checked when making release public).
- _Unpin_ old release announcement thread.
- _Pin_ the release announcement thread, for Discussions and for Announcements category.
--

* Announce new release on https://forum.lazarus.freepascal.org/[Lazarus forum].
+
--
- To convert our Markdown changelog/announcement to bbcode, https://pandoc.org/installing.html[install latest pandoc] (at least 3.8.3) and run: `pandoc --from=gfm --to=bbcode n.md --output=n.bbcode`
- Add a paragraph explaining what we are. `PasDoc is a documentation generator for Pascal source code. Documentation is generated from comments found in the source code (or in special description files). We support many output formats, like HTML, LaTeX (for PDF, PS), XML and PHP. We are free open-source software.`
--
* fpc-pascal mailing list (`[ANN] PasDoc X.Y.Z release`)
* https://castle-engine.io/wp/[Castle Game Engine news]
* Debian Pascal packaging mailing list
* https://sourceforge.net/p/pasdoc/news/[SourceForge "Old News" item] _PasDoc x.y.z released_
* Announce new release on http://freshcode.club/projects/pasdoc.
* Send an update to http://directory.fsf.org/project/pasdoc/[FSF directory].

* Post to Delphi / FPC communities on FB:
+
--
- https://www.facebook.com/groups/lazide
- https://www.facebook.com/groups/freepascallazarusdelphi
- https://www.facebook.com/groups/DelphiDevelopers/
- https://www.facebook.com/groups/170041353008050 - Pascal Game Development
- https://www.facebook.com/groups/2326037874 - Pascal programming language
- https://www.facebook.com/groups/137012246341854 - Delphi developer
--
+
Sample post: https://www.facebook.com/groups/lazide/posts/3320318151558389/

* Post to https://en.delphipraxis.net/forum/13-delphi-third-party/[Delphi Praxis] forum, in "Delphi Third Party" section.
+
Sample: https://en.delphipraxis.net/topic/7480-castle-game-engine-70-alpha2-release/

* LinkedIn: https://www.linkedin.com/groups/1290947/

Really, really large and significant improvements may be signalled by
changing the project's description:

* on https://github.com/pasdoc/pasdoc/[GitHub]
* on https://sourceforge.net/projects/pasdoc/[SF project page]
* on http://wiki.lazarus.freepascal.org/Projects_using_Lazarus#PasDoc[Lazarus wiki "Projects Using Lazarus" page]

## Prepare for next release

* `ChangeLog.md` file should start with line
+
----
## Upcoming Next Release
----

- Repeat the steps from _"Change version number to next stable"_, but :
+
--
- Make last version number _odd_ to signify unstable release and add `.snapshot`, like `1.2.5.snapshot`.

- Update link:DevelopmentSnapshots[DevelopmentSnapshots] version number.

- Remove from [snapshot release](https://github.com/pasdoc/pasdoc/releases/tag/snapshot) old version numbered archives.
--

* Switch back `release_tag: snapshot` in `.github/workflows/build.yml`.